layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
     - app-landing-page
     - Dotfiles

social_media:
  linkedin: romanmazeev
  telegram: CoreAnimation
  twitter: romanmazeev
  instagram: romanmazeev
  vk: romanmazeev

topics:
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png
    
  - name: iOS
    web_url: https://github.com/topics/ios
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ios/ios.png
    
  - name: MacOS
    web_url: https://github.com/topics/macos
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/macos/macos.png
  
  - name: Machine learning
    web_url: https://github.com/topics/machine-learning
    
  - name: Deep learning
    web_url: https://github.com/topics/deep-learning
    
  - name: Continuous integration
    web_url: https://github.com/topics/continuous-integration
    

  

    
    
    
    
    
